mutation CreateRequest(
  $userEmail: String!
  $machineId: UUID!
  $description: String!
  $requestDate: Timestamp!
  $mechanicEmail: String!
) @auth(level: PUBLIC) {
  request_insert(
    data: {
      user: { email: $userEmail }
      machine: { id: $machineId }
      mechanic: { email: $mechanicEmail }
      description: $description
      status: "Pending"
      requestDate: $requestDate
    }
  )
}

mutation UpdateRoutine($id: UUID!, $isCheck: Boolean!) @auth(level: PUBLIC) {
  routine_update(id: $id, data: { isCheck: $isCheck })
}

# Update Request Status
mutation UpdateRequestStatus($id: UUID!, $status: String!)
@auth(level: PUBLIC) {
  request_update(id: $id, data: { status: $status })
}

mutation CreateItem($name: String!, $quantity: Int!, $description: String!)
@auth(level: PUBLIC) {
  item_insert(
    data: { name: $name, quantity: $quantity, description: $description }
  )
}

mutation CreateMachine(
  $name: String!
  $serialNumber: String!
  $description: String!
) @auth(level: PUBLIC) {
  machine_insert(
    data: {
      name: $name
      serialNumber: $serialNumber
      description: $description
    }
  )
}

mutation CreateUser(
  $email: String!
  $password: String!
  $name: String!
  $role: String!
  $tel: String!
) @auth(level: PUBLIC) {
  user_insert(
    data: {
      email: $email
      password: $password
      name: $name
      role: $role
      tel: $tel
    }
  )
}

mutation CreateMaintainLog(
  $title: String!
  $isDone: Boolean!
  $machineId: UUID!
) @auth(level: PUBLIC) {
  maintainLog_insert(
    data: { title: $title, isDone: $isDone, machine: { id: $machineId } }
  )
}
