# User Queries
query GetUser($email: String!) @auth(level: PUBLIC) {
  user(key: {email: $email}) {
    email
    name
    role
    tel
  }
}

query ListUsers @auth(level: PUBLIC) {
  users {
    email
    name
    role
    tel
  }
}

query GetMechanics @auth(level: PUBLIC) {
  users(where: {role: {eq: "mechanic"}}) {
    email
    name
    role
    tel
  }
}

# Machine Queries
query GetMachine($id: UUID!) @auth(level: PUBLIC) {
  machine(id: $id) {
    id
    name
    serialNumber
    description
  }
}

query ListMachines @auth(level: PUBLIC) {
  machines {
    id
    name
    serialNumber
    description
  }
}

# Item Queries
query GetItem($id: UUID!) @auth(level: PUBLIC) {
  item(id: $id) {
    id
    name
    quantity
    description
  }
}

query ListItems @auth(level: PUBLIC) {
  items {
    id
    name
    quantity
    description
  }
}

# Request Queries
query GetRequest($id: UUID!) @auth(level: PUBLIC) {
  request(id: $id) {
    id
    user {
      email
      name
    }
    machine {
      id
      name
    }
    requestDate
    description
    status
  }
}

query ListRequests @auth(level: PUBLIC) {
  requests {
    id
    user {
      email
      name
    }
    machine {
      id
      name
    }
    requestDate
    description
    status
  }
}

query GetRequestsByMechanicEmail($email: String!) @auth(level: PUBLIC) {
  requests(where: {mechanicEmail: {eq: $email}}) {
    id
    user {
      email
      name
    }
    machine {
      id
      name
    }
    requestDate
    description
    status
  }
}


# Routine Queries
query GetRoutine($id: UUID!) @auth(level: PUBLIC) {
  routine(id: $id) {
    id
    machine {
      id
      name
    }
    title
    description
    isCheck
  }
}

query GetRoutinesByMachineId($machineId: UUID!) @auth(level: PUBLIC) {
  routines(where: {machineId: {eq: $machineId}}) {
    id
    title
    description
    isCheck
  }
}

# RoutineLog Queries
query GetRoutineLog($id: UUID!) @auth(level: PUBLIC) {
  routineLog(id: $id) {
    id
    title
    isDone
    routine {
      id
      title
    }
  }
}

query ListRoutineLogs @auth(level: PUBLIC) {
  routineLogs {
    id
    title
    isDone
    routine {
      id
      title
    }
  }
}

# MaintainLog Queries
query GetMaintainLog($id: UUID!) @auth(level: PUBLIC) {
  maintainLog(id: $id) {
    id
    title
    isDone
    machine {
      id
      name
    }
  }
}

query ListMaintainLogs @auth(level: PUBLIC) {
  maintainLogs {
    id
    title
    isDone
    machine {
      id
      name
    }
  }
}
