// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
        appId: '1:954777026389:web:fbcd5b68cd888f6d6d79dc',
        messagingSenderId: '954777026389',
        projectId: 'fir-factory-45cec',
        authDomain: 'fir-factory-45cec.firebaseapp.com',
        storageBucket: 'fir-factory-45cec.firebasestorage.app',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
        appId: '1:954777026389:android:804c6e7d6c821fc06d79dc',
        messagingSenderId: '954777026389',
        projectId: 'fir-factory-45cec',
        storageBucket: 'fir-factory-45cec.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
        appId: '1:954777026389:ios:357c6105f0d8a8c46d79dc',
        messagingSenderId: '954777026389',
        projectId: 'fir-factory-45cec',
        storageBucket: 'fir-factory-45cec.firebasestorage.app',
        androidClientId:
            '954777026389-g83fmevk1jqb0ad37ps0oe587h89k4fn.apps.googleusercontent.com',
        iosClientId:
            '954777026389-jq5t9f3baapsv45je0qgd47e3lqr13f4.apps.googleusercontent.com',
        iosBundleId: 'com.example.sFactory',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_MACOS'] ?? '',
        appId: '1:954777026389:ios:357c6105f0d8a8c46d79dc',
        messagingSenderId: '954777026389',
        projectId: 'fir-factory-45cec',
        storageBucket: 'fir-factory-45cec.firebasestorage.app',
        androidClientId:
            '954777026389-g83fmevk1jqb0ad37ps0oe587h89k4fn.apps.googleusercontent.com',
        iosClientId:
            '954777026389-jq5t9f3baapsv45je0qgd47e3lqr13f4.apps.googleusercontent.com',
        iosBundleId: 'com.example.sFactory',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '',
        appId: '1:954777026389:web:a7f1740c3f68e5936d79dc',
        messagingSenderId: '954777026389',
        projectId: 'fir-factory-45cec',
        authDomain: 'fir-factory-45cec.firebaseapp.com',
        storageBucket: 'fir-factory-45cec.firebasestorage.app',
      );
}