type User @table(key: "email") {
  email: String!
  password: String!
  name: String
  role: String
  tel: String
  fcmToken: String
  imageUrl: String
  createdAt: Timestamp @default(expr: "request.time")
  updatedAt: Timestamp @default(expr: "request.time")
}

type Machine @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  name: String
  serialNumber: Int
  description: String
  imageUrl: String
  createdAt: Timestamp @default(expr: "request.time")
  updatedAt: Timestamp @default(expr: "request.time")
}

type Item @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  name: String
  quantity: Int
  description: String
  imageUrl: String
  createdAt: Timestamp @default(expr: "request.time")
  updatedAt: Timestamp @default(expr: "request.time")
}

type Request @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  user: User!
  machine: Machine!
  mechanic: User!
  requestDate: Timestamp!
  description: String
  status: String @default(value: "Pending")
  createdAt: Timestamp @default(expr: "request.time")
  updatedAt: Timestamp @default(expr: "request.time")
}

type Routine @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  machine: Machine!
  creator: User
  title: String
  description: String
  isCheck: Boolean @default(value: false)
  createdAt: Timestamp @default(expr: "request.time")
  updatedAt: Timestamp @default(expr: "request.time")
}

type RoutineLog @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  routine: Routine!
  title: String
  isDone: Boolean
  createdAt: Timestamp @default(expr: "request.time")
}

type MaintainLog @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  title: String
  isDone: Boolean
  machine: Machine!
  mechanic: User
  createdAt: Timestamp @default(expr: "request.time")
}

type Notification @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  mechanic: User!
  request: Request!
  title: String!
  body: String!
  isRead: Boolean @default(value: false)
  createdAt: Timestamp! @default(expr: "request.time")
}

type TaskItem @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  request: Request!
  item: Item!
  quantity: Int!
  createdAt: Timestamp @default(expr: "request.time")
  updatedAt: Timestamp @default(expr: "request.time")
}